# Generated by Django 6.0.1 on 2026-02-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='affiliation',
            field=models.CharField(default='University of the West of Scotland', max_length=200),
        ),
        migrations.AddField(
            model_name='program',
            name='level',
            field=models.CharField(choices=[('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate'), ('professional', 'Professional')], default='postgraduate', max_length=20),
        ),
        migrations.AlterField(
            model_name='program',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
    ]
