# Generated by Django 6.0.1 on 2026-02-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_staffprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoverningCouncil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(upload_to='council/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of appearance on the website')),
            ],
            options={
                'verbose_name': 'Governing Council Member',
                'verbose_name_plural': 'Governing Council Members',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='program',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
