# Generated by Django 6.0.1 on 2026-02-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_governingcouncil_alter_program_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='governingcouncil',
            name='bio',
            field=models.TextField(blank=True, help_text='Detailed information about the member.'),
        ),
    ]
