# Generated by Django 6.0.1 on 2026-02-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_courseregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseregistration',
            name='registration_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('resit', 'Resit / Re-take')], default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='study_month',
            field=models.CharField(default='not_specified', help_text='The month selected for study start.', max_length=20),
            preserve_default=False,
        ),
    ]
