# Generated by Django 6.0.1 on 2026-02-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_courseregistration_registration_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='affiliation',
            field=models.CharField(blank=True, default='University of the West of Scotland', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='level',
            field=models.CharField(choices=[('undergraduate', 'Qualifications for Professionals'), ('postgraduate', 'Postgraduate'), ('professional', 'Professional')], default='postgraduate', max_length=20),
        ),
    ]
