# Generated by Django 6.0.1 on 2026-02-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0008_alter_program_affiliation_alter_program_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='external_url',
            field=models.URLField(blank=True, help_text='Enter the unique external URL for this programme (e.g., https://ugc.edu.gh/your-link)', max_length=500, null=True),
        ),
    ]
