# Generated by Django 6.0.1 on 2026-02-15 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0009_program_external_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('floor', models.IntegerField(default=1)),
                ('capacity', models.IntegerField(default=4)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoomReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('student_id', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time_slot', models.CharField(choices=[('09:00-11:00', '09:00 - 11:00'), ('11:00-13:00', '11:00 - 13:00'), ('14:00-16:00', '14:00 - 16:00'), ('16:00-18:00', '16:00 - 18:00')], max_length=20)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='programs.studyroom')),
            ],
        ),
    ]
