# Generated by Django 6.0.1 on 2026-02-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0012_alter_roomreservation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
