# Generated by Django 6.0.1 on 2026-02-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0013_studentprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomreservation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
