# Generated by Django 6.0.1 on 2026-02-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0014_alter_roomreservation_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomreservation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='roomreservation',
            name='student_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
